version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "22:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  - "status: Waiting For Review"
  ignore:
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: concurrently
    versions:
    - 6.0.0
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.2.1
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: stylelint
    versions:
    - 13.12.0
    - 13.8.0
    - 13.9.0
  - dependency-name: y18n
    versions:
    - 3.2.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: "@storybook/addon-storysource"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: nested-object-assign
    versions:
    - 1.0.4
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: i18next-browser-languagedetector
    versions:
    - 6.0.1
  rebase-strategy: disabled
