name: Check danger

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: yarn

      # - name: Danger Review
      #   uses: MeilCli/danger-action@master
      #   with:
      #     plugins_file: 'Gemfile'
      #     danger_file: 'Dangerfile'
      #     danger_id: 'danger-pr'
      #   env:
      #     DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Notification Danger check
        if: always()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }}
          fields: repo,message,action,author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
