name: Check danger

on: pull_request

jobs:
  danger:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Install package
        run: yarn
        env:
          CI: true

      - name: Install bundler
        run: gem install bundler

      - name: Execute danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle --path vendor/bundle
          bundle exec danger

      - name: Slack Notification Danger check
        if: always()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ github.repository }}
          fields: repo,message,action,author
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
